server:
  port: 8088
spring:
  application:
    name: kafkanotificationrestapi

  r2dbc:
    url: r2dbc:postgres://postgres:5432/notification_rest_api
    username: postgres
    password: root

  flyway:
    url: jdbc:postgresql://postgres:5432/notification_rest_api
    locations: classpath:db/migration
    user: postgres
    password: root

  kafka:
    bootstrap-servers: kafka:9092
    topic: notification-topic
    consumer:
      group-id: notification_consumers
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false